[package]
name = "image_seam_carving"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
image = "0.25.1"

[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3
